services:
  - type: web
    name: flask-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Install Chrome dependencies
      apt-get update
      apt-get install -y wget gnupg unzip
      # Install Google Chrome
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
      # Install ChromeDriver
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
      wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*} -O /tmp/chromedriver_version
      CHROMEDRIVER_VERSION=$(cat /tmp/chromedriver_version)
      wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -P /tmp/
      unzip -o /tmp/chromedriver_linux64.zip -d /tmp/
      mv /tmp/chromedriver /usr/local/bin/chromedriver
      chmod +x /usr/local/bin/chromedriver
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app --timeout 300 --keep-alive 5 --max-requests 100
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
